/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oscode */

#ifndef _Included_oscode
#define _Included_oscode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oscode
 * Method:    readfile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_oscode_readfile
JNIEXPORT jstring JNICALL Java_com_example_ankitdave_ostextfilereader_MainActivity_readfile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
